const myGames = [
    // === ИГРЫ, ОБЪЕДИНЕННЫЕ СО STEAM И PS5 PRO ===
    { title: "Grand Theft Auto V", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "550.9 ч.", date: "10.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/3240220/library_600x900_2x.jpg" },
    { title: "Cyberpunk 2077", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "48.9 ч.", date: "06.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1091500/library_600x900_2x.jpg" },
    { title: "Battlefield 2042", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "47.0 ч.", date: "15.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1517290/library_600x900_2x.jpg" },
    { title: "Far Cry 5", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "33.2 ч.", date: "19.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/552520/library_600x900_2x.jpg" },
    { title: "Metro Exodus", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "27.5 ч.", date: "11.05.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/412020/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Valhalla", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "20.1 ч.", date: "29.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/2208920/library_600x900_2x.jpg" },
    { title: "Far Cry 6", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "8.2 ч.", date: "25.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/2369390/library_600x900_2x.jpg" },

    // === НОВЫЕ ИГРЫ ТОЛЬКО С PS5 PRO ===
    { title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl", rating: "", year: "", platform: "PS5 Pro", hours: "9.9 ч.", date: "01.09.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1643320/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man 2", rating: "", year: "", platform: "PS5 Pro", hours: "16.6 ч.", date: "30.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2651280/library_600x900_2x.jpg" },
    { title: "Call of Duty Modern Warfare III", rating: "", year: "", platform: "PS5 Pro", hours: "6.2 ч.", date: "28.07.2026", image: "https://store-images.s-microsoft.com/image/apps.55183.13612848337674936.f9e71e15-6765-4282-8a3d-968dccfb729c.f59acc22-2c7b-41fb-96ca-d173dc290712" },
    { title: "Avatar: Frontiers of Pandora", rating: "", year: "", platform: "PS5 Pro", hours: "5.1 ч.", date: "27.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2840770/library_600x900_2x.jpg" },
    { title: "Ghost of Yōtei", rating: "", year: "", platform: "PS5 Pro", hours: "10.6 ч.", date: "11.07.2026", image: "https://upload.wikimedia.org/wikipedia/en/1/18/Ghost_of_Y%C5%8Dtei_cover_art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "God of War", rating: "", year: "", platform: "PS5 Pro", hours: "6.3 ч.", date: "06.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1593500/library_600x900_2x.jpg" },
    { title: "Star Wars Outlaws", rating: "", year: "", platform: "PS5 Pro", hours: "1.2 ч.", date: "30.06.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2842040/library_600x900_2x.jpg" },
    { title: "The Last of Us Part II Remastered", rating: "", year: "", platform: "PS5 Pro", hours: "27.5 ч.", date: "13.05.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2531310/library_600x900_2x.jpg" },
    { title: "The Last of Us Part I", rating: "", year: "", platform: "PS5 Pro", hours: "27.5 ч.", date: "29.04.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1888930/library_600x900_2x.jpg" },
    { title: "Ghost of Tsushima", rating: "", year: "", platform: "PS5 Pro", hours: "39.5 ч.", date: "19.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2215430/library_600x900_2x.jpg" },
    { title: "Horizon Forbidden West", rating: "", year: "", platform: "PS5 Pro", hours: "36.2 ч.", date: "19.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2420110/library_600x900_2x.jpg" },
    { title: "Resident Evil 4", rating: "", year: "", platform: "PS5 Pro", hours: "13.8 ч.", date: "06.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2050650/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man: Miles Morales", rating: "", year: "", platform: "PS5 Pro", hours: "5.9 ч.", date: "19.02.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1817190/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man Remastered", rating: "", year: "", platform: "PS5 Pro", hours: "19.0 ч.", date: "11.02.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1817070/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Mirage", rating: "", year: "", platform: "PS5 Pro", hours: "1.0 ч.", date: "21.01.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/3035570/library_600x900_2x.jpg" },
    { title: "Dying Light 2: Stay Human", rating: "", year: "", platform: "PS5 Pro", hours: "6.7 ч.", date: "19.01.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/534380/library_600x900_2x.jpg" },
    { title: "Hogwarts Legacy", rating: "", year: "", platform: "PS5 Pro", hours: "1.2 ч.", date: "12.12.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/990080/library_600x900_2x.jpg" },
    { title: "DEATH STRANDING DIRECTOR'S CUT", rating: "", year: "", platform: "PS5 Pro", hours: "2.6 ч.", date: "22.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1850570/library_600x900_2x.jpg" },
    { title: "Uncharted: Legacy of Thieves Collection", rating: "", year: "", platform: "PS5 Pro", hours: "2.7 ч.", date: "22.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1659420/library_600x900_2x.jpg" },
    { title: "Battlefield 6", rating: "", year: "", platform: "PS5 Pro", hours: "1.0 ч.", date: "22.08.2026", image: "https://blackheartprints.com/cdn/shop/files/Battlefield6GamePosterWeb_1200x1200.jpg?v=1755121492" },
    { title: "Ratchet & Clank: Rift Apart", rating: "", year: "", platform: "PS5 Pro", hours: "7.6 ч.", date: "09.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1895880/library_600x900_2x.jpg" },
    { title: "Resident Evil Requiem", rating: "", year: "", platform: "PS5 Pro", hours: "6.6 ч.", date: "09.08.2026", image: "https://upload.wikimedia.org/wikipedia/ru/c/c1/Resident_Evil_Requiem.jpg?utm_source=ru.wikipedia.org&utm_campaign=index&utm_content=original" },

    // === ОСТАЛЬНЫЕ ИГРЫ ТОЛЬКО ИЗ STEAM ===
    { title: "Tom Clancy's Rainbow Six Siege", rating: "", year: "", platform: "PC (Steam)", hours: "692.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/359550/library_600x900_2x.jpg" },
    { title: "Cities: Skylines", rating: "", year: "", platform: "PC (Steam)", hours: "485.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/255710/library_600x900_2x.jpg" },
    { title: "Cities: Skylines II", rating: "", year: "", platform: "PC (Steam)", hours: "201.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/949230/library_600x900_2x.jpg" },
    { title: "Satisfactory", rating: "", year: "", platform: "PC (Steam)", hours: "142.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/526870/library_600x900_2x.jpg" },
    { title: "Red Dead Redemption 2", rating: "", year: "", platform: "PC (Steam)", hours: "64.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1174180/library_600x900_2x.jpg" },
    { title: "Just Cause 3", rating: "", year: "", platform: "PC (Steam)", hours: "63.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/225540/library_600x900_2x.jpg" },
    { title: "METAL GEAR SOLID V: THE PHANTOM PAIN", rating: "", year: "", platform: "PC (Steam)", hours: "43.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/287700/library_600x900_2x.jpg" },
    { title: "Red Dead Online", rating: "", year: "", platform: "PC (Steam)", hours: "42.4 ч.", date: "", image: "https://store-images.s-microsoft.com/image/apps.52937.14000656789288172.d4ada0e8-b4f0-4bbe-9de1-dd243275d3a4.0cb5038f-6e6a-458e-962c-38be6a873f9f" },
    { title: "Battlefield V", rating: "", year: "", platform: "PC (Steam)", hours: "40.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1238810/library_600x900_2x.jpg" },
    { title: "Transport Fever 2", rating: "", year: "", platform: "PC (Steam)", hours: "25.6 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1066780/library_600x900_2x.jpg" },
    { title: "Far Cry New Dawn", rating: "", year: "", platform: "PC (Steam)", hours: "18.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/939960/library_600x900_2x.jpg" },
    { title: "The Forest", rating: "", year: "", platform: "PC (Steam)", hours: "15.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/242760/library_600x900_2x.jpg" },
    { title: "PAYDAY 2", rating: "", year: "", platform: "PC (Steam)", hours: "15.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/218620/library_600x900_2x.jpg" },
    { title: "Grand Theft Auto IV: The Complete Edition", rating: "", year: "", platform: "PC (Steam)", hours: "12.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/12210/library_600x900_2x.jpg" },
    { title: "Max Payne 3", rating: "", year: "", platform: "PC (Steam)", hours: "8.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/204100/library_600x900_2x.jpg" },
    { title: "Alan Wake", rating: "", year: "", platform: "PC (Steam)", hours: "8.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/108710/library_600x900_2x.jpg" },
    { title: "Wallpaper Engine", rating: "", year: "", platform: "PC (Steam)", hours: "8.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/431960/library_600x900_2x.jpg" },
    { title: "Frostpunk", rating: "", year: "", platform: "PC (Steam)", hours: "7.6 ч.", date: "", image: "https://upload.wikimedia.org/wikipedia/ru/2/2b/%D0%9B%D0%BE%D0%B3%D0%BE%D1%82%D0%B8%D0%BF_%D0%B8%D0%B3%D1%80%D1%8B_Frostpunk.jpg?utm_source=ru.wikipedia.org&utm_campaign=index&utm_content=original" },
    { title: "Dying Light", rating: "", year: "", platform: "PC (Steam)", hours: "7.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/239140/library_600x900_2x.jpg" },
    { title: "Tomb Raider", rating: "", year: "", platform: "PC (Steam)", hours: "7.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/391220/library_600x900_2x.jpg" },
    { title: "The Witcher 2: Assassins of Kings Enhanced Edition", rating: "", year: "", platform: "PC (Steam)", hours: "6.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/20920/library_600x900_2x.jpg" },
    { title: "Townscaper", rating: "", year: "", platform: "PC (Steam)", hours: "6.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1291340/library_600x900_2x.jpg" },
    { title: "Prey", rating: "", year: "", platform: "PC (Steam)", hours: "5.9 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/480490/library_600x900_2x.jpg" },
    { title: "Titanfall 2", rating: "", year: "", platform: "PC (Steam)", hours: "5.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1237970/library_600x900_2x.jpg" },
    { title: "Detroit: Become Human", rating: "", year: "", platform: "PC (Steam)", hours: "5.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1222140/library_600x900_2x.jpg" },
    { title: "Borderlands 2", rating: "", year: "", platform: "PC (Steam)", hours: "4.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/49520/library_600x900_2x.jpg" },
    { title: "DOOM", rating: "", year: "", platform: "PC (Steam)", hours: "3.8 ч.", date: "", image: "https://image.api.playstation.com/vulcan/ap/rnd/202009/2814/GGyEnCkIXoyiVlN9sRHkzUPo.png" },
    { title: "Aimlabs", rating: "", year: "", platform: "PC (Steam)", hours: "2.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/714010/library_600x900_2x.jpg" },
    { title: "The Witcher 3: Wild Hunt - Complete Edition", rating: "", year: "", platform: "PC (Steam)", hours: "2.7 ч.", date: "", image: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "STAR WARS Jedi: Fallen Order", rating: "", year: "", platform: "PC (Steam)", hours: "2.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1172380/library_600x900_2x.jpg" },
    { title: "Deus Ex: Mankind Divided", rating: "", year: "", platform: "PC (Steam)", hours: "2.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/337000/library_600x900_2x.jpg" },
    { title: "Left 4 Dead 2", rating: "", year: "", platform: "PC (Steam)", hours: "1.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/550/library_600x900_2x.jpg" },
    { title: "DiRT Rally", rating: "", year: "", platform: "PC (Steam)", hours: "1.4 ч.", date: "", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdmDQjzncGiCyijQFxyTKWVA1_CoJ7lr1cZB78bn_70GVcOIPqe4gKlus&s=10" },
    { title: "Borderlands 2 RU", rating: "", year: "", platform: "PC (Steam)", hours: "1.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/49520/library_600x900_2x.jpg" },
    { title: "L.A. Noire", rating: "", year: "", platform: "PC (Steam)", hours: "1.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/110800/library_600x900_2x.jpg" },
    { title: "Far Cry 4", rating: "", year: "", platform: "PC (Steam)", hours: "1.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/298110/library_600x900_2x.jpg" },
    { title: "Little Nightmares Enhanced Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/en/d/d8/Little_Nightmares_Box_Art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "HITMAN World of Assassination", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1659040/library_600x900_2x.jpg" },
    { title: "Battlefield 1", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1238840/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Odyssey", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/812140/library_600x900_2x.jpg" },
    { title: "Prey: Typhon Hunter", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/741820/library_600x900_2x.jpg" },
    { title: "House Flipper", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://store-images.s-microsoft.com/image/apps.37810.13518543789452586.33e180bb-4f0b-4a39-b1c8-cde6206c1eb3.10ce0025-264d-4dfc-bf77-75601b68ec7e" },
    { title: "The Elder Scrolls V: Skyrim Special Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/489830/library_600x900_2x.jpg" },
    { title: "Little Nightmares", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/424840/library_600x900_2x.jpg" },
    { title: "Rise of the Tomb Raider", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/391220/library_600x900_2x.jpg" },
    { title: "Dead Island Riptide Definitive Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/383180/library_600x900_2x.jpg" },
    { title: "METAL GEAR SOLID V: GROUND ZEROES", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/en/0/07/MGSV_Ground_Zeroes_boxart.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Borderlands: The Pre-Sequel", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/261640/library_600x900_2x.jpg" },
    { title: "Metro 2033", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/286690/library_600x900_2x.jpg" },
    { title: "Just Cause 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/8190/library_600x900_2x.jpg" },
    { title: "Portal 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/620/library_600x900_2x.jpg" },
    { title: "Portal", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/ru/4/4e/Portal_boxcover.jpg?utm_source=ru.wikipedia.org&utm_campaign=index&utm_content=original" },
    { title: "Half-Life Deathmatch: Source", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/360/library_600x900_2x.jpg" },
    { title: "Half-Life 2: Deathmatch", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/320/library_600x900_2x.jpg" },
    { title: "Half-Life 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/220/library_600x900_2x.jpg" },
    { title: "Half-Life", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/70/library_600x900_2x.jpg" },
    { title: "Call of Duty®", rating: "", year: "", platform: "PS5 Pro", hours: "6.2 ч.", date: "", image: "https://image.api.playstation.com/vulcan/ap/rnd/202605/2815/e7c940f1c3b9c2725e08b10979926ed6b71482f6f42a65ba.png" },
    { title: "Call of Duty®: Modern Warfare® III", rating: "", year: "", platform: "PS5 Pro", hours: "6.2 ч.", date: "", image: "https://image.api.playstation.com/vulcan/ap/rnd/202407/0316/51b683f8a89f65bf8a3204eb43c46aba5741620709d4bdfa.png" },
    { title: "The Last of Us™ Part II", rating: "", year: "", platform: "PS5 Pro", hours: "27.5 ч.", date: "", image: "https://image.api.playstation.com/vulcan/img/rnd/202010/2618/w48z6bzefZPrRcJHc7L8SO66.png" },
    { title: "The Last of Us™ Part I", rating: "", year: "", platform: "PS5 Pro", hours: "27.5 ч.", date: "", image: "https://image.api.playstation.com/vulcan/ap/rnd/202206/0720/eEczyEMDd2BLa3dtkGJVE9Id.png" },
    { title: "FAR CRY®6", rating: "", year: "", platform: "PS5 Pro", hours: "1.4 ч.", date: "", image: "https://image.api.playstation.com/vulcan/img/rnd/202106/1514/xqoTYwf0S55ro6fwcIIY1KI4.png" },
    { title: "DEATH STRANDING™", rating: "", year: "", platform: "PS5 Pro", hours: "2.6 ч.", date: "", image: "https://image.api.playstation.com/vulcan/img/rnd/202009/2921/40aD0BqRUHyHdXdC6nwtwON5.png" },
];