const myGames = [
    // === ИГРЫ, ОБЪЕДИНЕННЫЕ СО STEAM И PS5 PRO ===
    { title: "Grand Theft Auto V", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "550.9 ч.", date: "10.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/3240220/library_600x900_2x.jpg" },
    { title: "Cyberpunk 2077", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "48.9 ч.", date: "06.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1091500/library_600x900_2x.jpg" },
    { title: "Battlefield 2042", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "47.0 ч.", date: "15.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1517290/library_600x900_2x.jpg" },
    { title: "Far Cry 5", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "33.2 ч.", date: "19.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/552520/library_600x900_2x.jpg" },
    { title: "Metro Exodus", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "27.5 ч.", date: "11.05.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/412020/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Valhalla", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "20.1 ч.", date: "29.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/2208920/library_600x900_2x.jpg" },
    { title: "Far Cry 6", rating: "", year: "", platform: "PC (Steam) + PS5 Pro", hours: "8.2 ч.", date: "25.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/2369390/library_600x900_2x.jpg" },

    // === НОВЫЕ ИГРЫ ТОЛЬКО С PS5 PRO ===
    { title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl", rating: "", year: "", platform: "PS5 Pro", hours: "9.9 ч.", date: "01.09.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1643320/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man 2", rating: "", year: "", platform: "PS5 Pro", hours: "16.6 ч.", date: "30.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2651280/library_600x900_2x.jpg" },
    { title: "Call of Duty Modern Warfare III", rating: "", year: "", platform: "PS5 Pro", hours: "6.2 ч.", date: "28.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/3595270/library_600x900_2x.jpg" },
    { title: "Avatar: Frontiers of Pandora", rating: "", year: "", platform: "PS5 Pro", hours: "5.1 ч.", date: "27.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2840770/library_600x900_2x.jpg" },
    { title: "Ghost of Yōtei", rating: "", year: "", platform: "PS5 Pro", hours: "10.6 ч.", date: "11.07.2026", image: "https://upload.wikimedia.org/wikipedia/en/1/18/Ghost_of_Y%C5%8Dtei_cover_art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Overwatch", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "07.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2357570/library_600x900_2x.jpg" },
    { title: "God of War", rating: "", year: "", platform: "PS5 Pro", hours: "6.3 ч.", date: "06.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1593500/library_600x900_2x.jpg" },
    { title: "Worms Rumble", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "04.07.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1186040/library_600x900_2x.jpg" },
    { title: "Star Wars Outlaws", rating: "", year: "", platform: "PS5 Pro", hours: "1.2 ч.", date: "30.06.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2842040/library_600x900_2x.jpg" },
    { title: "The Last of Us Part II Remastered", rating: "", year: "", platform: "PS5 Pro", hours: "27.5 ч.", date: "13.05.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2531310/library_600x900_2x.jpg" },
    { title: "Sackboy: A Big Adventure", rating: "", year: "", platform: "PS5 Pro", hours: "0.2 ч.", date: "13.05.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1599660/library_600x900_2x.jpg" },
    { title: "The Last of Us Part I", rating: "", year: "", platform: "PS5 Pro", hours: "13.6 ч.", date: "29.04.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1888930/library_600x900_2x.jpg" },
    { title: "Horizon Zero Dawn Remastered", rating: "", year: "", platform: "PS5 Pro", hours: "0.8 ч.", date: "22.04.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2561580/library_600x900_2x.jpg" },
    { title: "The Crew Motorfest", rating: "", year: "", platform: "PS5 Pro", hours: "0.5 ч.", date: "22.04.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2698940/library_600x900_2x.jpg" },
    { title: "Ghost of Tsushima", rating: "", year: "", platform: "PS5 Pro", hours: "39.5 ч.", date: "19.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2215430/library_600x900_2x.jpg" },
    { title: "Horizon Forbidden West", rating: "", year: "", platform: "PS5 Pro", hours: "36.2 ч.", date: "19.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2420110/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Unity", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "19.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/289650/library_600x900_2x.jpg" },
    { title: "Resident Evil 4", rating: "", year: "", platform: "PS5 Pro", hours: "13.8 ч.", date: "06.03.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2050650/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man: Miles Morales", rating: "", year: "", platform: "PS5 Pro", hours: "5.9 ч.", date: "19.02.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1817190/library_600x900_2x.jpg" },
    { title: "Marvel's Spider-Man Remastered", rating: "", year: "", platform: "PS5 Pro", hours: "19.0 ч.", date: "11.02.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1817070/library_600x900_2x.jpg" },
    { title: "Highguard", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "03.02.2026", image: "https://upload.wikimedia.org/wikipedia/en/f/fe/Highguard_key_art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Subnautica: Below Zero", rating: "", year: "", platform: "PS5 Pro", hours: "0.2 ч.", date: "03.02.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/848450/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Mirage", rating: "", year: "", platform: "PS5 Pro", hours: "1.0 ч.", date: "21.01.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/3035570/library_600x900_2x.jpg" },
    { title: "Planet Coaster 2", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "21.01.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2688950/library_600x900_2x.jpg" },
    { title: "Dying Light 2: Stay Human", rating: "", year: "", platform: "PS5 Pro", hours: "6.7 ч.", date: "19.01.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/534380/library_600x900_2x.jpg" },
    { title: "Hogwarts Legacy", rating: "", year: "", platform: "PS5 Pro", hours: "1.2 ч.", date: "12.12.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/990080/library_600x900_2x.jpg" },
    { title: "Tropico 6", rating: "", year: "", platform: "PS5 Pro", hours: "0.2 ч.", date: "06.12.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/492720/library_600x900_2x.jpg" },
    { title: "Red Dead Redemption", rating: "", year: "", platform: "PS5 Pro", hours: "0.3 ч.", date: "02.12.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1174180/library_600x900_2x.jpg" },
    { title: "Anno 1800", rating: "", year: "", platform: "PS5 Pro", hours: "0.2 ч.", date: "23.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/916440/library_600x900_2x.jpg" },
    { title: "DEATH STRANDING DIRECTOR'S CUT", rating: "", year: "", platform: "PS5 Pro", hours: "2.6 ч.", date: "22.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1850570/library_600x900_2x.jpg" },
    { title: "Uncharted: Legacy of Thieves Collection", rating: "", year: "", platform: "PS5 Pro", hours: "2.7 ч.", date: "22.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1659420/library_600x900_2x.jpg" },
    { title: "Insurgency: Sandstorm", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "19.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/581320/library_600x900_2x.jpg" },
    { title: "SONIC FRONTIERS", rating: "", year: "", platform: "PS5 Pro", hours: "0.1 ч.", date: "18.11.2025", image: "https://upload.wikimedia.org/wikipedia/en/0/0f/SonicFrontiersCoverArt.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Returnal", rating: "", year: "", platform: "PS5 Pro", hours: "0.8 ч.", date: "17.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/1649240/library_600x900_2x.jpg" },
    { title: "Watch Dogs: Legion", rating: "", year: "", platform: "PS5 Pro", hours: "0.4 ч.", date: "16.11.2025", image: "https://steamcdn-a.akamaihd.net/steam/apps/2239550/library_600x900_2x.jpg" },
    { title: "Battlefield 6", rating: "", year: "", platform: "PS5 Pro", hours: "1.0 ч.", date: "22.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/2807960/library_600x900_2x.jpg" },
    { title: "Helldivers 2", rating: "", year: "", platform: "PS5 Pro", hours: "0.6 ч.", date: "16.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/553850/library_600x900_2x.jpg" },
    { title: "Ratchet & Clank: Rift Apart", rating: "", year: "", platform: "PS5 Pro", hours: "7.6 ч.", date: "09.08.2026", image: "https://steamcdn-a.akamaihd.net/steam/apps/1895880/library_600x900_2x.jpg" },
    { title: "Resident Evil Requiem - EU", rating: "", year: "", platform: "PS5 Pro", hours: "6.6 ч.", date: "09.08.2026", image: "https://placehold.co/400x600/1e1e1e/a0a0a0?text=RE+Requiem" },

    // === ОСТАЛЬНЫЕ ИГРЫ ТОЛЬКО ИЗ STEAM ===
    { title: "Tom Clancy's Rainbow Six Siege", rating: "", year: "", platform: "PC (Steam)", hours: "682.6 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/359550/library_600x900_2x.jpg" },
    { title: "Cities: Skylines", rating: "", year: "", platform: "PC (Steam)", hours: "485.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/255710/library_600x900_2x.jpg" },
    { title: "Cities: Skylines II", rating: "", year: "", platform: "PC (Steam)", hours: "201.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/949230/library_600x900_2x.jpg" },
    { title: "Satisfactory", rating: "", year: "", platform: "PC (Steam)", hours: "142.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/526870/library_600x900_2x.jpg" },
    { title: "Red Dead Redemption 2", rating: "", year: "", platform: "PC (Steam)", hours: "64.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1174180/library_600x900_2x.jpg" },
    { title: "Just Cause 3", rating: "", year: "", platform: "PC (Steam)", hours: "63.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/225540/library_600x900_2x.jpg" },
    { title: "METAL GEAR SOLID V: THE PHANTOM PAIN", rating: "", year: "", platform: "PC (Steam)", hours: "43.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/287700/library_600x900_2x.jpg" },
    { title: "Red Dead Online", rating: "", year: "", platform: "PC (Steam)", hours: "42.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1404210/library_600x900_2x.jpg" },
    { title: "Battlefield V", rating: "", year: "", platform: "PC (Steam)", hours: "40.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1238810/library_600x900_2x.jpg" },
    { title: "Transport Fever 2", rating: "", year: "", platform: "PC (Steam)", hours: "25.6 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1066780/library_600x900_2x.jpg" },
    { title: "Far Cry New Dawn", rating: "", year: "", platform: "PC (Steam)", hours: "18.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/939960/library_600x900_2x.jpg" },
    { title: "The Forest", rating: "", year: "", platform: "PC (Steam)", hours: "15.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/242760/library_600x900_2x.jpg" },
    { title: "PAYDAY 2", rating: "", year: "", platform: "PC (Steam)", hours: "15.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/218620/library_600x900_2x.jpg" },
    { title: "Grand Theft Auto IV: The Complete Edition", rating: "", year: "", platform: "PC (Steam)", hours: "12.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/12210/library_600x900_2x.jpg" },
    { title: "Tom Clancy's Rainbow Six Siege - Test Server", rating: "", year: "", platform: "PC (Steam)", hours: "10.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/359550/library_600x900_2x.jpg" },
    { title: "Max Payne 3", rating: "", year: "", platform: "PC (Steam)", hours: "8.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/204100/library_600x900_2x.jpg" },
    { title: "Alan Wake", rating: "", year: "", platform: "PC (Steam)", hours: "8.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/108710/library_600x900_2x.jpg" },
    { title: "Wallpaper Engine", rating: "", year: "", platform: "PC (Steam)", hours: "8.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/431960/library_600x900_2x.jpg" },
    { title: "Frostpunk", rating: "", year: "", platform: "PC (Steam)", hours: "7.6 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1601580/library_600x900_2x.jpg" },
    { title: "Dying Light", rating: "", year: "", platform: "PC (Steam)", hours: "7.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/239140/library_600x900_2x.jpg" },
    { title: "Tomb Raider", rating: "", year: "", platform: "PC (Steam)", hours: "7.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/391220/library_600x900_2x.jpg" },
    { title: "The Witcher 2: Assassins of Kings Enhanced Edition", rating: "", year: "", platform: "PC (Steam)", hours: "6.3 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/20920/library_600x900_2x.jpg" },
    { title: "Townscaper", rating: "", year: "", platform: "PC (Steam)", hours: "6.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1291340/library_600x900_2x.jpg" },
    { title: "Prey", rating: "", year: "", platform: "PC (Steam)", hours: "5.9 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/480490/library_600x900_2x.jpg" },
    { title: "Titanfall 2", rating: "", year: "", platform: "PC (Steam)", hours: "5.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1237970/library_600x900_2x.jpg" },
    { title: "Detroit: Become Human", rating: "", year: "", platform: "PC (Steam)", hours: "5.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1222140/library_600x900_2x.jpg" },
    { title: "Borderlands 2", rating: "", year: "", platform: "PC (Steam)", hours: "4.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/49520/library_600x900_2x.jpg" },
    { title: "DOOM", rating: "", year: "", platform: "PC (Steam)", hours: "3.8 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/3017860/library_600x900_2x.jpg" },
    { title: "Aimlabs", rating: "", year: "", platform: "PC (Steam)", hours: "2.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/714010/library_600x900_2x.jpg" },
    { title: "The Witcher 3: Wild Hunt - Complete Edition", rating: "", year: "", platform: "PC (Steam)", hours: "2.7 ч.", date: "", image: "https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "STAR WARS Jedi: Fallen Order", rating: "", year: "", platform: "PC (Steam)", hours: "2.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1172380/library_600x900_2x.jpg" },
    { title: "Deus Ex: Mankind Divided", rating: "", year: "", platform: "PC (Steam)", hours: "2.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/337000/library_600x900_2x.jpg" },
    { title: "Left 4 Dead 2", rating: "", year: "", platform: "PC (Steam)", hours: "1.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/550/library_600x900_2x.jpg" },
    { title: "DiRT Rally", rating: "", year: "", platform: "PC (Steam)", hours: "1.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/690790/library_600x900_2x.jpg" },
    { title: "Borderlands 2 RU", rating: "", year: "", platform: "PC (Steam)", hours: "1.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/49520/library_600x900_2x.jpg" },
    { title: "L.A. Noire", rating: "", year: "", platform: "PC (Steam)", hours: "1.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/110800/library_600x900_2x.jpg" },
    { title: "Far Cry 4", rating: "", year: "", platform: "PC (Steam)", hours: "1.0 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/298110/library_600x900_2x.jpg" },
    { title: "HITMAN 2", rating: "", year: "", platform: "PC (Steam)", hours: "0.9 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/6850/library_600x900_2x.jpg" },
    { title: "Archibald", rating: "", year: "", platform: "PC (Steam)", hours: "0.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/461480/library_600x900_2x.jpg" },
    { title: "Metro: Last Light Complete Edition", rating: "", year: "", platform: "PC (Steam)", hours: "0.7 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/287390/library_600x900_2x.jpg" },
    { title: "Metro Exodus Enhanced Edition", rating: "", year: "", platform: "PC (Steam)", hours: "0.5 ч.", date: "", image: "https://upload.wikimedia.org/wikipedia/en/a/af/Cover_Art_of_Metro_Exodus.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Iron Sky Invasion", rating: "", year: "", platform: "PC (Steam)", hours: "0.5 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/224900/library_600x900_2x.jpg" },
    { title: "Sleeping Dogs: Definitive Edition", rating: "", year: "", platform: "PC (Steam)", hours: "0.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/202170/library_600x900_2x.jpg" },
    { title: "Banished", rating: "", year: "", platform: "PC (Steam)", hours: "0.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1863430/library_600x900_2x.jpg" },
    { title: "Just Cause 3: Multiplayer Mod", rating: "", year: "", platform: "PC (Steam)", hours: "0.4 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/225540/library_600x900_2x.jpg" },
    { title: "Apex Legends", rating: "", year: "", platform: "PC (Steam)", hours: "0.2 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1172470/library_600x900_2x.jpg" },
    { title: "Two Worlds II Castle Defense", rating: "", year: "", platform: "PC (Steam)", hours: "0.1 ч.", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/7530/library_600x900_2x.jpg" },
    { title: "Little Nightmares Enhanced Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/en/d/d8/Little_Nightmares_Box_Art.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "HITMAN World of Assassination", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1659040/library_600x900_2x.jpg" },
    { title: "Battlefield 1", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1238840/library_600x900_2x.jpg" },
    { title: "Assassin's Creed Odyssey", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/812140/library_600x900_2x.jpg" },
    { title: "Prey: Typhon Hunter", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/741820/library_600x900_2x.jpg" },
    { title: "Numberline 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/654970/library_600x900_2x.jpg" },
    { title: "House Flipper", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/1190970/library_600x900_2x.jpg" },
    { title: "The Elder Scrolls V: Skyrim Special Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/489830/library_600x900_2x.jpg" },
    { title: "Warhammer 40,000: Gladius - Relics of War", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/en/9/9e/Warhammer_40%2C000_Gladius_Relics_of_War_cover.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Minion Masters", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/489520/library_600x900_2x.jpg" },
    { title: "Little Nightmares", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/424840/library_600x900_2x.jpg" },
    { title: "ARK: Survival Of The Fittest", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/407530/library_600x900_2x.jpg" },
    { title: "Rise of the Tomb Raider", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/391220/library_600x900_2x.jpg" },
    { title: "Dead Island Riptide Definitive Edition", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/383180/library_600x900_2x.jpg" },
    { title: "ARK: Survival Evolved", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/346110/library_600x900_2x.jpg" },
    { title: "METAL GEAR SOLID V: GROUND ZEROES", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://upload.wikimedia.org/wikipedia/en/0/07/MGSV_Ground_Zeroes_boxart.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail_unscaled" },
    { title: "Borderlands: The Pre-Sequel", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/261640/library_600x900_2x.jpg" },
    { title: "Company of Heroes 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/231430/library_600x900_2x.jpg" },
    { title: "Metro 2033", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/286690/library_600x900_2x.jpg" },
    { title: "Total War: SHOGUN 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/201270/library_600x900_2x.jpg" },
    { title: "Just Cause 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/8190/library_600x900_2x.jpg" },
    { title: "Portal 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/620/library_600x900_2x.jpg" },
    { title: "Portal", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/620/library_600x900_2x.jpg" },
    { title: "Half-Life Deathmatch: Source", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/360/library_600x900_2x.jpg" },
    { title: "Half-Life 2: Deathmatch", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/320/library_600x900_2x.jpg" },
    { title: "Half-Life 2", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/220/library_600x900_2x.jpg" },
    { title: "Half-Life", rating: "", year: "", platform: "PC (Steam)", hours: "", date: "", image: "https://steamcdn-a.akamaihd.net/steam/apps/70/library_600x900_2x.jpg" }
];